Enrichments:
  CoolEnrichment: #This is just an identifier and wont be shown in game. Make sure no 2 enrichments share the same identifier
    DisplayName: "Test Enrichment" #This is the display name shown in game
    Item: "DIAMOND_SWORD" #This is the item that will appear in game as the enrichment icon
    Cost: 1250 #This is the cost of the enrichment.
    Perks:
      1: #This is the name of the tier shown in the item lore. You can make it whatever you want but make it easy for players to understand
        Types: #The types of buffs you recieve at this tier. You can add as many as you want, but make sure to only include each one once
          - SPEED
          - JUMP_HEIGHT
        Effects: #The effects. Make sure the position of the buff matches the position of the type. For instance here it would be +2 speed and +3 jump height
          - 2
          - 3
      2: #Another tier
        TierCount: 10 #The amount of XP needed on an item to tier up. DO NOT put this on the first tier
        Types:
          - SPEED
          - JUMP_HEIGHT
        Effects:
          - 50
          - 50
      3:
        TierCount: 100
        Types:
          - SPEED
          - JUMP_HEIGHT
        Effects:
          - 1
          - 1
    TierType: KILL #The type of action needed to gain XP. At the moment KILL is the only option.
    TierSubType: ZOMBIE #The thing that it tracks. For instance here its tracking zombie kills. Simply state the entity tyoe to track it
    WhitelistedItems: #The items the enrichment can be applied to. Putting SWORD, SHOVEL, PICKAXE, AXE, HOE, HELMET, CHESTPLATE, LEGGINGS, or BOOTS will count for all types of that item
      - BOW
      - HELMET
      - IRON_BLOCK