name: ItemEnrichments
main: com.pigslayer.itemenrichments.Main
version: 1.14
api-version: 1.13
author: PigSlayer18
depend: [Vault,NBTAPI]
commands:
  enrichitem:
    usage: /<command>
    description: Enrich your items!
    permission: itemenrichments.usemenu
  debugxp:
    usage: /<command>
    description: Debug command. Gives enrichment XP
    permission: itemenrichments.admin
  editenrich:
    usage: /<command>
    description: Allows editing of enrichments in game
    permission: itemenrichments.admin
  enrichmentsreload:
    usage: /<command>
    description: Reload the configuration of ItemEnrichments
    permission: itemenrichments.admin
permissions:
  itemenrichments.*:
    description: Gives access to all ItemEnrichments Permission nodes
    children:
      itemenrichments.admin: true
      itemenrichments.usemenu: true
      itemenrichments.useenrichments: true
  itemenrichments.admin:
    description: Gives access to admin/debug commands for ItemEnrichments
  itemenrichments.usemenu:
    description: Gives access to use /enrichitem
    children:
      itemenrichments.useenrichments: true
  itemenrichments.useenrichments:
    description: Gives access to use enrichments on items.